services:
  - type: web
    name: ngCash
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node dist/shared/http/server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.ofquxucuvinakriqhuzg:Scarif2024$@aws-1-us-west-2.pooler.supabase.com:6543/postgres
      - key: NODE_ENV
        value: development

