services:
  - type: web
    name: ngCash
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node dist/shared/http/server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Scarif2024$@db.ofquxucuvinakriqhuzg.supabase.co:5432/postgres
      - key: NODE_ENV
        value: development

