services:
  - type: web
    name: ngCash
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node dist/shared/http/server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://thiago:Scarif2024$@projetos-tl.c7i88oiykryo.us-east-2.rds.amazonaws.com:5432/projetos-tl?schema=public
      - key: NODE_ENV
        value: production
